### ISSUE TITLE
UnknownError: 2 root error(s) found.   (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.

### ISSUE THREAD

**Issue by irdanish11** [irdanish11/AnomalyEventDetection#1]
UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node conv3d/Conv3D}}]]
	 [[metrics/acc/Identity/_183]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node conv3d/Conv3D}}]]
0 successful operations.
0 derived errors ignored.

**Comment by irdanish11** [comment]
This error I got on my machine due to out of memory (The trace back didn't told me that), I found out because 4th solution (Given below) worked for me. And interesting thing was that I had two machines with following specs:

### Machine 1:
1. *OS:*           Windows 10 x64  
2. *GPU:*         GTX 1060 6GB,  
3. *Cuda:*       10.0, 
4. *CuDNN:*    v7.6.4.38 
5. *TF:*             1.15 GPU
6. *conda/pip?* Installed using ``` pip install tensorflow-gpu==1.15 ```
7. *Python:*      3.7

### Machine 2:
1. *OS:*           Windows 10 x64  
2. *GPU:*         GTX 1660 Ti 6GB,  
3. *Cuda:*       10.0, 
4. *CuDNN:*    v7.6.4.38 
5. *TF:*             1.15 GPU
6. *conda/pip?* Installed using ``` pip install tensorflow-gpu==1.15 ```
7. *Python:*      3.7

The code worked on Machine 1 very well but on Machine 2 it will give the error: *Failed to get convolution algorithm. This is probably because cuDNN failed to initialize*. In my case 2nd solution in 4 part (the last one) solved my issue.

I've seen this error message for four different reasons, with different solutions: 

### 1. You have cache issues
I regularly work around this error by shutting down my python process, removing the ~/.nv directory (on linux, rm -rf ~/.nv), and restarting the Python process. I don't exactly know why this works. It's probably at least partly related to the second option:

### 2. You're out of memory
The error can also show up if you run out of graphics card RAM. With an nvidia GPU you can check graphics card memory usage with nvidia-smi. This will give you not only a readout of how much GPU RAM you have in use (something like 6025MiB /  6086MiB if you're almost at the limit) as well as a list of what processes are using GPU RAM.

If you've run out of RAM, you'll need to restart the process (which should free up the RAM) and then take a less memory-intensive approach. A few options are:

reducing your batch size
using a simpler model
using less data
limit TensorFlow GPU memory fraction: For example, the following will make sure TensorFlow uses <= 90% of your RAM:
```
import keras
import tensorflow as tf

config = tf.ConfigProto()
config.gpu_options.per_process_gpu_memory_fraction = 0.9
keras.backend.tensorflow_backend.set_session(tf.Session(config=config))
```

This can slow down your model evaluation if not used together with the items above, presumably since the large data set will have to be swapped in and out to fit into the small amount of memory you've allocated.

### 3. You have incompatible versions of CUDA, TensorFlow, NVIDIA drivers, etc.
If you've never had similar models working, you're not running out of VRAM and your cache is clean, I'd go back and set up CUDA + TensorFlow using the best available installation guide - I have had the most success with following the instructions at https://www.tensorflow.org/install/gpu rather than those on the NVIDIA / CUDA site. Lambda Stack: https://lambdalabs.com/lambda-stack-deep-learning-software is also a good way to go.

### 4. While using Keras, Keras layers(classes) were directly imported from keras instead of tensorflow.keras 

Keras is included in TensorFlow 2.0 above. So

remove ``` import keras ``` and
replace ``` from keras.module.module import class ``` statement to --> from ``` tensorflow.keras.module.module import class ```

For example
Replace 
``` from keras.layers import Conv3D,ConvLSTM2D,Conv3DTranspose, Input```
with this:
``` from tensorflow.keras.layers import Conv3D,ConvLSTM2D,Conv3DTranspose, Input ```

Maybe your GPU memory is filled. So use allow ``` growth = True ``` in GPU option. This is deprecated now. But use this below code snippet after imports may solve your problem.

```
import tensorflow as tf
from tensorflow.compat.v1.keras.backend import set_session


config = tf.compat.v1.ConfigProto()
config.gpu_options.allow_growth = True  # dynamically grow the memory used on the GPU
config.log_device_placement = True  # to log device placement (on which device the operation ran)
sess = tf.compat.v1.Session(config=config)
set_session(sess)
print('\nTensorflow GPU installed: '+str(tf.test.is_built_with_cuda()))
print('Is Tensorflow using GPU: \n'+str(tf.test.is_gpu_available()))
```
### If the above code does not resolve the issue then try the following code, and put the following write after imports:
```
import tensorflow as tf
 gpus = tf.config.experimental.list_physical_devices('GPU')
    #The variable GB is the memory size you want to use.
    config = [tf.config.experimental.VirtualDeviceConfiguration(memory_limit=(1024*GB))]
    if gpus:
      # Restrict TensorFlow to only allocate 1*X GB of memory on the first GPU
      try:
        tf.config.experimental.set_virtual_device_configuration(gpus[0], config)
        logical_gpus = tf.config.experimental.list_logical_devices('GPU')
        print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
      except RuntimeError as e:
        # Virtual devices must be set before GPUs have been initialized
        print(e)
``` 

In the above code at line#4 the Variable GB represents the memory you want to to use from your total memory of GPU. It is recommended to use at least 1 GB less than your total GPU Memory size. If still problem exist try lowering the value of the Variable GB. Eventually it will work.

**Comment by irdanish11** [comment]
Issue resolved
